--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP


fx_version 'bodacious'
games { 'gta5' }
this_is_a_map 'yes'

--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--https://discord.gg/XHTBdFcfNP
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5
--  https://discord.gg/h24Uavz5